apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-nfs
spec:
  sotrageClassName: nfs
  capacity:
    storage: 1Gi
  accessMode:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: <NFS_SERVER_IP>