name: my-back
replicaCount: 1
image:
  repository: chanchan0314/my-back
  tag: latest
containerPort: 8000
servicePort: 8000
env:
  DB_HOST: db
  DB_PORT: "5432"
  DB_NAME: mydb
  DB_USER: admin
  DB_PASSWORD: new1234!

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: localhost
      paths:
        - path: /api
          pathType: Prefix