apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-backend
  template:
    metadata:
      labels:
        app: my-backend
    spec:
      containers:
        - name: backend
          image: <백엔드 이미지:태그> # 빌드 후 이미지 레지스트리에 올리고, 경로 작성
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "my-postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "admin"
            - name: DB_PASSWORD
              value: "new1234!"
            - name: DB_NAME
              value: "mydb"
